/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba;

import com.toedter.calendar.JDateChooser;
import dao.ActivosDao;
import dao.DAOCustomException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Activos;
import mysqlDao.MySQLActivosDao;
import util.Utilitarios;

/**
 *
 * @author jsanchez
 */
public class FormularioPrueba extends javax.swing.JFrame {

    DefaultListModel modelo = new DefaultListModel();
    Utilitarios util = new Utilitarios();

    /**
     * Creates new form FormularioPrueba
     */
    public FormularioPrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ComboMoneda = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        textCodigo = new javax.swing.JTextField();
        textArticulo = new javax.swing.JTextField();
        textNumero_ser = new javax.swing.JTextField();
        textMarca = new javax.swing.JTextField();
        textPrecio_com = new javax.swing.JTextField();
        textPrecio_act = new javax.swing.JTextField();
        textPeso = new javax.swing.JTextField();
        textUbicacion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCodigo = new javax.swing.JList<>();
        btnArtNuevo = new javax.swing.JButton();
        JDCfecha = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setText("Codigo");

        jLabel2.setText("Articulo");

        jLabel3.setText("numero_ser");

        jLabel4.setText("marca");

        jLabel5.setText("fecha");

        jLabel6.setText("precio_com");

        jLabel7.setText("precio_act");

        jLabel8.setText("peso");

        jLabel9.setText("ubicacion");

        jLabel10.setText("Moneda");

        ComboMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "US$", "S/" }));
        ComboMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMonedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        textCodigo.setToolTipText("Codigo Articulo");
        textCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodigoActionPerformed(evt);
            }
        });

        textArticulo.setToolTipText("Nombre Articulo");

        textNumero_ser.setToolTipText("Numero de Serial");
        textNumero_ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumero_serActionPerformed(evt);
            }
        });

        textMarca.setToolTipText("Marca Articulo");

        textPrecio_com.setToolTipText("precio de venta");
        textPrecio_com.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPrecio_comKeyTyped(evt);
            }
        });

        textPrecio_act.setToolTipText("Precio Actual");
        textPrecio_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrecio_actActionPerformed(evt);
            }
        });
        textPrecio_act.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPrecio_actKeyTyped(evt);
            }
        });

        textPeso.setToolTipText("Peso Articulo");
        textPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPesoKeyTyped(evt);
            }
        });

        textUbicacion.setToolTipText("Ubicacion en Almacen");
        textUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUbicacionActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        listCodigo.setToolTipText("Lista Articulos Agregados");
        listCodigo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listCodigoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listCodigo);

        btnArtNuevo.setText("Nuevo Articulo");
        btnArtNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtNuevoActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar Todos");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textUbicacion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(textNumero_ser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                                .addComponent(textPrecio_com, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                                .addComponent(textPrecio_act, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                                .addComponent(textPeso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(textMarca, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(JDCfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(textArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(224, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnArtNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnSalir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textNumero_ser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(JDCfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textPrecio_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textPrecio_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(textUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ComboMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar)
                    .addComponent(btnArtNuevo)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18))
        );

        btnSalir.getAccessibleContext().setAccessibleName("btnSalir");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboMonedaActionPerformed

    private void textCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodigoActionPerformed

    private void textNumero_serActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumero_serActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumero_serActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            ejecutarUpdate();
        } catch (ParseException ex) {
            Logger.getLogger(FormularioPrueba.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnArtNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtNuevoActionPerformed

        ejecutarInsert();

    }//GEN-LAST:event_btnArtNuevoActionPerformed

    private void textUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUbicacionActionPerformed

    private void listCodigoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listCodigoValueChanged
        Connection con;

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/sistematic_net1", "juan", "juan123");
            ActivosDao dao = new MySQLActivosDao(con);
            String codigoSelect = listCodigo.getSelectedValue();
            Activos act = dao.findByCode(codigoSelect);
            RellenarCampos(act);
        } catch (SQLException | DAOCustomException ex) {
            Logger.getLogger(FormularioPrueba.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_listCodigoValueChanged

    private void textPrecio_comKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPrecio_comKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_textPrecio_comKeyTyped

    private void textPrecio_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrecio_actActionPerformed

    }//GEN-LAST:event_textPrecio_actActionPerformed

    private void textPrecio_actKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPrecio_actKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_textPrecio_actKeyTyped

    private void textPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPesoKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_textPesoKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            rellenarLista();
        } catch (SQLException ex) {
            Logger.getLogger(FormularioPrueba.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DAOCustomException ex) {
            Logger.getLogger(FormularioPrueba.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Realmente desea salir del Mantimiento tabla Productos?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== 0){
            dispose();
        }

    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboMoneda;
    private com.toedter.calendar.JDateChooser JDCfecha;
    private javax.swing.JButton btnArtNuevo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listCodigo;
    private javax.swing.JTextField textArticulo;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textMarca;
    private javax.swing.JTextField textNumero_ser;
    private javax.swing.JTextField textPeso;
    private javax.swing.JTextField textPrecio_act;
    private javax.swing.JTextField textPrecio_com;
    private javax.swing.JTextField textUbicacion;
    // End of variables declaration//GEN-END:variables

    public void ejecutarInsert() {
        Activos act = null;
        if ((textCodigo != null && textCodigo.getText().length() > 0
                && textArticulo != null && textArticulo.getText().length() > 0
                && textNumero_ser != null && textNumero_ser.getText().length() > 0
                && textMarca != null && textMarca.getText().length() > 0
                //                | jTextField5 != null && jTextField5.getText().length() > 0
                && textPrecio_com != null && textPrecio_com.getText().length() > 0
                && textPrecio_act != null && textPrecio_act.getText().length() > 0
                && textPeso != null && textPeso.getText().length() > 0
                && textUbicacion != null && textUbicacion.getText().length() > 0
                && JDCfecha != null && JDCfecha.getDate() != null)) {
            try {
                act = CrearActivosDeFormulario(textCodigo, textArticulo, textNumero_ser, textMarca, textPrecio_com, textPrecio_act, ComboMoneda, textPeso, textUbicacion, JDCfecha);
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sistematic_net1", "juan", "juan123");
                ActivosDao dao = new MySQLActivosDao(con);

                if (con == null) {
                    JOptionPane.showMessageDialog(null, "No se realizo la conexion con la BD, chequea la conexion");
                } else {
                    try {
                        if (dao.findByCode(act.getCodigo()) != null) {
                            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea modificarlo?", "Articulo ya Existe!", JOptionPane.YES_NO_OPTION);
                            if (resp == 0) {
//                                dao.update(act);
                                dao.delete(dao.findByCode(act.getCodigo()));
                                dao.insert(act);
//                                VaciarCampos();
                                JOptionPane.showMessageDialog(null, "Articulo Modificado exitosamente");

                            } else {
                                JOptionPane.showMessageDialog(null, "No se modifico el articulo");
                            }
                        } else {
                            dao.insert(act);
                            modelo.addElement(act.getCodigo());
                            listCodigo.setModel(modelo);
//                            VaciarCampos();
                        }

                    } catch (DAOCustomException ex) {
                        Logger.getLogger(FormularioPrueba.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (ParseException ex) {
                Logger.getLogger(FormularioPrueba.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FormularioPrueba.class.getName()).log(Level.SEVERE, null, ex);
            }
            {

            }
        } else {
            JOptionPane.showMessageDialog(null, "Tiene al menos un campo vacio");
        }

    }

    private void ejecutarUpdate() throws ParseException {
        Activos act = null;
        if ((textCodigo != null && textCodigo.getText().length() > 0
                && textArticulo != null && textArticulo.getText().length() > 0
                && textNumero_ser != null && textNumero_ser.getText().length() > 0
                && textMarca != null && textMarca.getText().length() > 0
                //                | jTextField5 != null && jTextField5.getText().length() > 0
                && textPrecio_com != null && textPrecio_com.getText().length() > 0
                && textPrecio_act != null && textPrecio_act.getText().length() > 0
                && textPeso != null && textPeso.getText().length() > 0
                && textUbicacion != null && textUbicacion.getText().length() > 0
                && JDCfecha != null && JDCfecha.getDate() != null)) {
            try {
                act = CrearActivosDeFormulario(textCodigo, textArticulo, textNumero_ser, textMarca, textPrecio_com, textPrecio_act, ComboMoneda, textPeso, textUbicacion, JDCfecha);
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sistematic_net1", "juan", "juan123");
                ActivosDao dao = new MySQLActivosDao(con);

                if (con == null) {
                    JOptionPane.showMessageDialog(null, "No se realizo la conexion con la BD, chequea la conexion");
                } else {
                    try {
                        if (dao.findByCode(act.getCodigo()) == null) {
                            JOptionPane.showMessageDialog(null, "Por favor agregelo como Articulo Nuevo", "Articulo NO Existe!", JOptionPane.WARNING_MESSAGE);
                        } else {
                            //dao.update(act);
                            dao.delete(dao.findByCode(act.getCodigo()));
                            dao.insert(act);
//                            VaciarCampos();
                            JOptionPane.showMessageDialog(null, "Articulo Modificado exitosamente");
                        }

                    } catch (DAOCustomException ex) {
                        Logger.getLogger(FormularioPrueba.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(FormularioPrueba.class.getName()).log(Level.SEVERE, null, ex);
            }
            {

            }
        } else {
            JOptionPane.showMessageDialog(null, "Tiene al menos un campo vacio");
        }
    }

    private Activos CrearActivosDeFormulario(JTextField codig, JTextField articul, JTextField numeroSe,
            JTextField marc, JTextField precio_co, JTextField precio_ac, JComboBox moned,
            JTextField pes, JTextField ubicacio, JDateChooser jd) throws ParseException {

        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        java.util.Date dateStr;
        Activos act = null;
        String codigo = codig.getText();
        String articulo = articul.getText();
        String numeroSer = numeroSe.getText();
        String marca = marc.getText();
//        dateStr = formatter.parse(fech.getText());
        Double precio_com = Double.parseDouble(precio_co.getText());
        Double precio_act = Double.parseDouble(precio_ac.getText());
        String moneda = moned.getSelectedItem().toString();
        Double peso = Double.parseDouble(pes.getText());
        String ubicacion = ubicacio.getText();
        act = new Activos(codigo, articulo, numeroSer, marca, jd.getDate(), precio_com, precio_act, moneda, peso, ubicacion);

        return act;
    }

    private void RellenarCampos(Activos object) {
        textCodigo.setText(object.getCodigo());
        textArticulo.setText(object.getArticulo());
        textNumero_ser.setText(object.getNumeroSer());
        textMarca.setText(object.getMarca());
//        SimpleDateFormat parseador = new SimpleDateFormat("dd-MM-yyyy");
        JDCfecha.setDate(object.getFecha());
//        jTextField5.setText(parseador.format(object.getFecha()));
        textPrecio_com.setText(String.valueOf(object.getPrecioCom()));
        textPrecio_act.setText(String.valueOf(object.getPrecioAct()));
        textPeso.setText(String.valueOf(object.getPeso()));
        textUbicacion.setText(object.getUbicacion());
        ComboMoneda.setSelectedItem(object.getMoneda());
    }

    private void VaciarCampos() {
        Date fecha = new Date();
        textCodigo.setText("");
        textArticulo.setText("");
        textNumero_ser.setText("");
        textMarca.setText("");
//        jTextField5.setText("dd-MM-yyyy");
        textPrecio_com.setText(String.valueOf(""));
        textPrecio_act.setText(String.valueOf(""));
        textPeso.setText(String.valueOf(""));
        textUbicacion.setText("");
    }

    private void rellenarLista() throws SQLException, DAOCustomException {

        List<Activos> lista = new ArrayList<>();

        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sistematic_net1", "juan", "juan123");
        ActivosDao dao = new MySQLActivosDao(con);

        if (con == null) {
            JOptionPane.showMessageDialog(null, "No se realizo la conexion con la BD, chequea la conexion");
        } else {
            lista = dao.findAll();
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No hay nada que mostrar");
            } else {
                modelo.clear();
                for (Activos act : lista) {
                    modelo.addElement(act.getCodigo());
                }
                listCodigo.setModel(modelo);
            }
        }
    }

}
